### ISSUE TITLE
Deploy a version with the Other tag fix

### ISSUE THREAD

**Issue by luchotc** [gobstones/gobstones-cli#12]
We should release a version that includes https://github.com/gobstones/gobstones-cli/commit/7f372ac3c3bc57fd794f01e96a6e2a13914a4d0e but doesn't include the batch re-order while we are fixing that.

@rodri042

**Comment by rodri042** [comment]
I can see in https://www.npmjs.com/package/gobstones-cli that 3.2.1 was published 13 days ago, same as https://github.com/gobstones/gobstones-cli/commit/7f372ac3c3bc57fd794f01e96a6e2a13914a4d0e

I think it's already published. Please reopen the issue if I'm wrong!
